name: cd
run-name: ${{ github.actor }} is running CD
on: [push, workflow_dispatch]

permissions:
  id-token: write
  contents: read

jobs:
  ui:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ui
    steps:
      - uses: actions/checkout@v6

      - uses: pnpm/action-setup@v4
        with:
          version: 11
      - uses: actions/setup-node@v7
        with:
          cache: pnpm
          cache-dependency-path: ui/pnpm-lock.yaml
          node-version: "26"
      - run: pnpm install --frozen-lockfile
      - run: pnpm build

      - uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: ${{ vars.AWS_GITHUB_ACTIONS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}
          role-skip-session-tagging: true

      - run: aws s3 sync ./dist "s3://${{ vars.SKIPLI_BUCKET_NAME }}/ui" --delete
