name: cicd
run-name: ${{ github.actor }} is running CI/CD
on: [push]

permissions:
  id-token: write
  contents: read

jobs:
  ui:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ap-southeast-1
      S3_UI_BUCKET: s3://skipli-797848269974-ap-southeast-7-an/
    defaults:
      run:
        working-directory: ui
    steps:
      - uses: actions/checkout@v6

      - uses: pnpm/action-setup@v4
        with:
          version: 11
      - uses: actions/setup-node@v7
        with:
          cache: pnpm
          cache-dependency-path: ui/pnpm-lock.yaml
          node-version: "26"
      - run: pnpm install --frozen-lockfile
      - run: pnpm build

      - uses: ./.github/actions/configure-aws-with-act
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-deploy-role-arn: ${{ vars.AWS_DEPLOY_ROLE_ARN }}

      - run: aws sts get-caller-identity
      - run: aws s3 sync ./dist $S3_UI_BUCKET --delete

  infra:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      # For future changeset review
      # - uses: ./.github/actions/configure-aws-with-act-aws-with-act

      - run: aws cloudformation validate-template --template-body file://infra/api.yaml
